In [3]:
import networkx as nx
import itertools
import random
import numpy as np
from datetime import datetime
from utils import *
from tqdm import tqdm
from scipy.sparse import dia_matrix
from collections import Counter

In [2]:
!pip uninstall scipy -y
!pip install scipy==1.8.0

!pip uninstall networkx -y
!pip install networkx==2.6

^C
ERROR: Operation cancelled by user
Found existing installation: networkx 2.6
Uninstalling networkx-2.6:
  Successfully uninstalled networkx-2.6
  Using cached networkx-2.6-py3-none-any.whl (1.9 MB)
Reason for being yanked: Need to resolve: https://github.com/networkx/networkx/pull/4967


In [ ]:
def super_secret_strategy(filename, n_seeds):
  curr_time = datetime.now()
  
  G = get_graph_from_file(f'sample_graphs/{filename}')
  c_deg = dict(G.degree())
  degs = np.array(list(c_deg.values())) + 1
  probs = degs / np.sum(degs)
  nodes = optimized_sim.create_nodes(nx.to_dict_of_lists(G))
  deg_nodes = sorted(c_deg.keys(), key=lambda x : c_deg[x], reverse=True)
  print([(i, c_deg[i]) for i in deg_nodes])
  deg_nodes = deg_nodes[:n_seeds]
  print(f'Degree nodes: {deg_nodes}')

  wins = {}
  previously_tried = set()

  while (datetime.now() - curr_time).total_seconds() < 10*60:
    seed = frozenset(np.random.choice(G.nodes(), n_seeds, replace=False, p=probs))
    
    if seed not in previously_tried:
      rand, deg = score_seeds_opt(seed, deg_nodes, nodes)
      previously_tried.add(seed)
      if rand > deg:
        wins[seed] = rand
        print(f'{seed} beat degrees {rand} to {deg}')

  if len(wins) == 0:
    return [frozenset(deg_nodes)]

  return wins

        

In [ ]:
super_secret_strategy('RR.5.10.json', 5)

[('35', 14), ('185', 14), ('20', 12), ('125', 11), ('220', 11), ('108', 10), ('117', 10), ('133', 10), ('160', 10), ('233', 10), ('307', 10), ('24', 9), ('30', 9), ('49', 9), ('68', 9), ('106', 9), ('145', 9), ('148', 9), ('170', 9), ('179', 9), ('182', 9), ('187', 9), ('204', 9), ('205', 9), ('214', 9), ('230', 9), ('248', 9), ('259', 9), ('286', 9), ('4', 8), ('17', 8), ('43', 8), ('50', 8), ('53', 8), ('73', 8), ('91', 8), ('109', 8), ('147', 8), ('158', 8), ('159', 8), ('171', 8), ('208', 8), ('215', 8), ('218', 8), ('235', 8), ('255', 8), ('269', 8), ('272', 8), ('288', 8), ('291', 8), ('0', 7), ('9', 7), ('18', 7), ('29', 7), ('41', 7), ('56', 7), ('84', 7), ('86', 7), ('88', 7), ('98', 7), ('100', 7), ('107', 7), ('121', 7), ('123', 7), ('156', 7), ('177', 7), ('181', 7), ('194', 7), ('196', 7), ('234', 7), ('237', 7), ('238', 7), ('242', 7), ('249', 7), ('260', 7), ('275', 7), ('279', 7), ('312', 7), ('5', 6), ('6', 6), ('14', 6), ('21', 6), ('34', 6), ('45', 6), ('46', 6), ('5

{frozenset({'158', '185', '214', '286', '50'}): 170.0,
 frozenset({'125', '185', '187', '20', '279'}): 160.0}

In [ ]:
Gsmall = get_graph_from_file(f'sample_graphs/RR.5.10.json')
btwn_small = nx.betweenness_centrality(Gsmall)
most = sorted(Gsmall.nodes(), key=lambda x : btwn_small[x], reverse=True)
print(most)

['155', '109', '137', '28', '24', '9', '73', '96', '8', '82', '195', '171', '163', '107', '77', '150', '133', '121', '199', '101', '145', '146', '74', '173', '71', '40', '143', '149', '36', '91', '85', '44', '59', '32', '179', '103', '175', '122', '97', '208', '4', '63', '182', '176', '20', '112', '159', '190', '125', '197', '52', '27', '16', '49', '38', '184', '132', '6', '72', '81', '124', '41', '167', '140', '116', '111', '198', '164', '201', '141', '202', '162', '181', '15', '148', '110', '180', '90', '60', '53', '13', '157', '10', '100', '89', '5', '185', '50', '93', '200', '75', '196', '104', '115', '120', '70', '55', '117', '14', '47', '95', '205', '26', '156', '113', '152', '33', '1', '114', '2', '189', '79', '129', '98', '99', '106', '166', '135', '161', '151', '170', '11', '29', '119', '54', '144', '46', '138', '102', '105', '7', '66', '78', '168', '37', '160', '136', '51', '45', '17', '108', '84', '25', '177', '207', '19', '154', '3', '194', '22', '204', '58', '142', '130', 

In [ ]:
to_test = frozenset(["35", "185", "220", "117", "125"])
deg_nodes = frozenset(['35', '185', '20', '125', '220'])
nodes = optimized_sim.create_nodes(nx.to_dict_of_lists(get_graph_from_file(f'sample_graphs/RR.5.10.json')))

winning_strats = [frozenset(['158', '185', '214', '286', '50']), frozenset(['125', '185', '187', '20', '279'])]

for strat in winning_strats:
    (us, them) = score_seeds_opt(strat, to_test, nodes)
    print(us, them)

150.0 150.0
140.0 169.0


In [ ]:
super_secret_strategy('RR.10.30.json', 10)

[('155', 12), ('82', 11), ('8', 10), ('28', 10), ('96', 10), ('137', 10), ('9', 9), ('24', 9), ('73', 9), ('107', 9), ('109', 9), ('121', 9), ('163', 9), ('103', 8), ('145', 8), ('171', 8), ('20', 7), ('36', 7), ('40', 7), ('52', 7), ('59', 7), ('72', 7), ('77', 7), ('85', 7), ('91', 7), ('97', 7), ('122', 7), ('133', 7), ('143', 7), ('146', 7), ('149', 7), ('150', 7), ('173', 7), ('195', 7), ('208', 7), ('4', 6), ('5', 6), ('6', 6), ('16', 6), ('32', 6), ('38', 6), ('41', 6), ('44', 6), ('49', 6), ('63', 6), ('74', 6), ('75', 6), ('81', 6), ('101', 6), ('111', 6), ('112', 6), ('125', 6), ('132', 6), ('141', 6), ('157', 6), ('159', 6), ('162', 6), ('175', 6), ('176', 6), ('179', 6), ('182', 6), ('190', 6), ('197', 6), ('199', 6), ('201', 6), ('202', 6), ('1', 5), ('10', 5), ('13', 5), ('14', 5), ('15', 5), ('26', 5), ('27', 5), ('33', 5), ('47', 5), ('50', 5), ('53', 5), ('55', 5), ('60', 5), ('70', 5), ('71', 5), ('79', 5), ('89', 5), ('90', 5), ('93', 5), ('95', 5), ('100', 5), ('110

{frozenset({'101',
            '116',
            '133',
            '137',
            '162',
            '197',
            '4',
            '59',
            '82',
            '94'}): 102.0,
 frozenset({'106',
            '116',
            '121',
            '137',
            '149',
            '155',
            '176',
            '59',
            '72',
            '82'}): 109.0}

In [ ]:
to_test = frozenset(["155", "107", "121", "195", "133", "109", "137", "24", "28", "73"])
nodes = optimized_sim.create_nodes(nx.to_dict_of_lists(get_graph_from_file(f'sample_graphs/RR.10.30.json')))
deg = frozenset(['155', '82', '8', '28', '96', '137', '9', '24', '73', '107'])
winning_strats = [frozenset(['107', '82', '149', '96', '155', '109', '103', '121', '148', '20']), frozenset(['133', '202', '82', '201', '149', '4', '40', '109', '163', '137'])]

for strat in winning_strats:
    print(f'strat vs test: {score_seeds_opt(strat, to_test, nodes)}')

strat vs test: (103.0, 98.0)
strat vs test: (79.0, 121.0)


In [ ]:
G = get_graph_from_file(f'sample_graphs/RR.10.30.json')
perc = {v : nx.local_reaching_centrality(G, v) for v in G.nodes()}
perc = sorted(G.nodes(), key=lambda x : perc[x], reverse=True)[:10]
print(perc)

['155', '9', '109', '28', '163', '24', '137', '107', '8', '96']


In [ ]:
vr = nx.voterank(G)[:10]
print(vr)

['155', '82', '28', '137', '8', '96', '121', '24', '107', '73']


In [ ]:
btwn = nx.betweenness_centrality(G)
most = sorted(G.nodes(), key=lambda x : btwn[x], reverse=True)[:10]
print(most)

['155', '109', '137', '28', '24', '9', '73', '96', '8', '82']


In [ ]:
res = nx.katz_centrality(G)
katz = sorted(G.nodes(), key=lambda x : res[x], reverse=True)[:10]
print(katz)

['155', '28', '109', '82', '96', '9', '8', '107', '137', '163']


In [ ]:
test = np.zeros(5)
print(test)

pts = frozenset([1,2])
pts2 = frozenset([1,2])

test[list(pts)] += 1
print(test)

test[list(pts)] -= 1
print(test)

print(pts == pts2)

[0. 0. 0. 0. 0.]
[0. 1. 1. 0. 0.]
[0. 0. 0. 0. 0.]
True


In [ ]:
test == None

array([False, False, False, False, False])

In [ ]:
np.sign(np.array([0,2,-5]))

array([ 0,  1, -1])

In [4]:
G = get_graph_from_file(f'sample_graphs/RR.10.51.json')

In [5]:
dia = 1.5 * np.ones(G.order())
adj = nx.adjacency_matrix(G) + np.diag(dia)


In [6]:
us = frozenset([6, 55, 163, 145, 2, 23, 107, 22, 148, 109])
them = frozenset([23, 148, 163, 55, 139, 6, 109, 145, 2, 22])

res1, res2 = optimized_sim.sim_1v1(adj, us, them)

TypeError: unhashable type: 'numpy.ndarray'

In [ ]:
print(res1, res2)

0 1


In [ ]:
then = datetime.now()
n = 5000

for _ in range(n):
    _, _ = optimized_sim.sim_1v1(adj, us, them)

print((datetime.now() - then).total_seconds() / n)

0.0078873268


In [ ]:
G = get_graph_from_file(f'sample_graphs/RR.10.51.json')
nodes = optimized_sim.create_nodes(nx.to_dict_of_lists(G))

us = frozenset(["6", "55", "163", "145", "2", "23", "107", "22", "148", "109"])
them = frozenset(["23", "148", "163", "55", "139", "6", "109", "145", "2", "22"])

then = datetime.now()

for _ in range(500):
    _, _ = score_seeds_opt(us, them, nodes)

print((datetime.now() - then).total_seconds())

14.829986


In [ ]:
0.0039139178000000005
0.0042473716

In [ ]:
x = np.matrix([0,1,2,3,4])
y = np.array(x)[0]

t = Counter(y)
t

Counter({0: 1, 1: 1, 2: 1, 3: 1, 4: 1})